### ISSUE TITLE
Building in Indigo

### ISSUE THREAD

**Issue by droter** [ros-drivers/kvh_drivers#1]
I cloned the package but when I run catkin_make from the workspace directory the package isn't found.

**Comment by jeff-o** [comment]
This package should be built using rosbuild; it has not been migrated yet.  So there are two options, you could upgrade the package to catkin (recommended) or build it using rosbuild.

Rosbuild: http://wiki.ros.org/rosbuild
Migrating from rosbuild: http://wiki.ros.org/catkin/migrating_from_rosbuild

If you'd like to take a crack at migrating the package that would be fantastic.  Unfortunately I no longer have the physical device to properly test the result.

**Comment by jeff-o** [comment]
Well I had a bit of time so I played around with porting to Indigo, along with a bit of cleanup here and there.  Everything built OK so I moved it into the master branch.  Please give it a try and let me know how it goes.  It's still far from a complete and robust driver, as it lacks error handling.  Of course, if you make any upgrades be sure to issue a pull request!

**Comment by droter** [comment]
Hi Jeff,

I tested the package today and it is working great.

Thanks for your help,

Matt
