### ISSUE TITLE
Move the present contents into a subdirectory

### ISSUE THREAD

**Issue by mikepurvis** [ros-drivers/kvh_drivers#3]
Thinking of a package with a better name than `kvh`, like `kvh_dsp3000_driver` or similar.

**Comment by geoffviola** [comment]
Is this still an issue? The package has been renamed to kvh_drivers. Even though it only contains a driver for the dsp3000, the intention is to put all KVH drivers here based on the documentation.

**Comment by mikepurvis** [comment]
Agree, I think it's fine the way it is.
