### ISSUE TITLE
Support for 1000hz model

### ISSUE THREAD

**Issue by ghost** [ros-drivers/kvh_drivers#4]
Hi,
Does this package support the 1000hz model

**Comment by geoffviola** [comment]
This driver has been tested a lot for the DSP 3000's incremental angle mode at 100Hz. Previously, it was used for the rate mode. It should support rate and integrated angle. It can change modes, but it can't change the frequency that the sensor produces messages as far as I can tell.

If you need the precision and not the responsiveness, you can try the incremental angle mode at 100Hz. That way the sensor samples at 1000Hz and reports the delta angle. Less data should be lost through integration as opposed to the rates.

**Comment by ghost** [comment]
The protocol for 1000hz is different. I have got this to work. Will make a PR after its made compatible with this package
