### ISSUE TITLE
Launch file pkg is wrong

### ISSUE THREAD

**Issue by Nurgak** [ros-drivers/kvh_drivers#5]
I think the `pkg` attribute in `dsp3000.launch` file should be `kvh` instead of `dsp3000`. Otherwise I get the following error:
```
ERROR: cannot launch node of type [dsp3000/dsp3000]: dsp3000
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/galar/catkin_ws/src
ROS path [2]=/opt/ros/indigo/share
ROS path [3]=/opt/ros/indigo/stacks
```

**Comment by geoffviola** [comment]
Yeah, that launch file is confusing. The user should only have to modify the device port configuration item and not the pkg. It should be fixed with https://github.com/ros-drivers/kvh_drivers/commit/f2497dd9a74d3eea3878156c6a38ff89c9eff872.
