### ISSUE TITLE
Confusing 'Indigo' branch?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-drivers/kvh_drivers#6]
The [Indigo](https://github.com/ros-drivers/kvh_drivers/tree/Indigo) branch was last updated 5 years ago and seems to still contain a rosbuild package.

`master` has seen more activity and was converted to Catkin in #2.

This seems to be confusing (at least some) users. See [how to replace rosbuild_link_boost() with the catkin macro](https://answers.ros.org/question/290768) on ROS Answers for instance.

Should the `Indigo` branch be removed?

**Comment by geoffviola** [comment]
Good point! Thanks for the comment. It's always easy to delete unused things. That was some legacy branch. I am unsure about the ROS branch structure. I believe master should support kinetic. I'm not sure about lunar.

**Comment by gavanderhoorn** [comment]
Thanks for clearing that up.

Would adding a short section to the readme explaining the status of the code (ie: on which platforms it builds and into which ROS versions it has been released) be an idea? 

The poster of the same question I linked had the impression that the package was "for Kinetic", solely based on the `rosdistro` entry. Clarifying that it should also work on Indigo (fi) could save potential users quite some confusion and perhaps even work.

**Comment by geoffviola** [comment]
I've only tested it on Kinetic intel x64. That's why there is only the kinetic entry on http://wiki.ros.org/kvh. That being said. I assume it works on indigo and lunar as well. To prove out the platforms, it should be worked into a CI system

**Comment by gavanderhoorn** [comment]
I've build-tested it on Indigo, so I know that works.

Don't have the hw though, so I can't test that.

But a CI would also not do that.

**Comment by gavanderhoorn** [comment]
I'd be willing to contribute a CI setup based on [industrial_ci](https://github.com/ros-industrial/industrial_ci). That should only take a couple of lines to test for multiple ROS releases ([example](https://github.com/ros-industrial/motoman/blob/a87015adee079370c6ea206ad4e538120e6e1a83/.travis.yml#L12-L25)).

You would have to enable Travis for that though.
